services:
  mongodb:
    image: mongo:6.0
    container_name: araragsys-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --auth

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: araragsys-milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
    depends_on: 
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: araragsys-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000